version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.0
jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/test
    
  integrateFrontend:
    docker:
       - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/DylanTardif/3w5-h22-tp2-frontend
      -
      -

workflows:
  build:
    jobs:
      - checkoutAndTest:
          filters:
            branches:
              only: main
