version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  integrateFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/DylanTardif/3w5-h22-tp2-frontend
      - run: git clone https://github.com/DylanTardif/3w5-h22-tp2-backend
      - run: ls -al
   
          
workflows:
  build:
    jobs:
      - checkoutAndTest:
          filters:
            branches:
              only: main
